# Generated by Django 4.2.5 on 2023-09-21 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0003_rename_list_date_listing_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='photo1',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='photo2',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='photo3',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='photo4',
        ),
        migrations.AddField(
            model_name='listing',
            name='photo',
            field=models.ImageField(default=None, upload_to='post_images'),
        ),
    ]
