# Generated by Django 4.2.5 on 2023-09-26 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0004_remove_listing_photo1_remove_listing_photo2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='text',
            new_name='desc',
        ),
        migrations.AddField(
            model_name='listing',
            name='detail_desc',
            field=models.TextField(default=None),
        ),
    ]
